<?php

/**
 * UploadApi
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BytescalePHP\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BytescalePHP\Client\ApiException;
use BytescalePHP\Client\Configuration;
use BytescalePHP\Client\HeaderSelector;
use BytescalePHP\Client\ObjectSerializer;

/**
 * UploadApi Class Doc Comment
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UploadApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation beginMultipartUpload
     *
     * Begins a new multipart file upload process.
     *
     * @param  \BytescalePHP\Client\Model\BeginMultipartUploadRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id account_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BytescalePHP\Client\Model\BeginMultipartUploadResponse
     */
    public function beginMultipartUpload($body, $account_id)
    {
        list($response) = $this->beginMultipartUploadWithHttpInfo($body, $account_id);
        return $response;
    }

    /**
     * Operation beginMultipartUploadWithHttpInfo
     *
     * Begins a new multipart file upload process.
     *
     * @param  \BytescalePHP\Client\Model\BeginMultipartUploadRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BytescalePHP\Client\Model\BeginMultipartUploadResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function beginMultipartUploadWithHttpInfo($body, $account_id)
    {
        $returnType = '\BytescalePHP\Client\Model\BeginMultipartUploadResponse';
        $request = $this->beginMultipartUploadRequest($body, $account_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\BeginMultipartUploadResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation beginMultipartUploadAsync
     *
     * Begins a new multipart file upload process.
     *
     * @param  \BytescalePHP\Client\Model\BeginMultipartUploadRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function beginMultipartUploadAsync($body, $account_id)
    {
        return $this->beginMultipartUploadAsyncWithHttpInfo($body, $account_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation beginMultipartUploadAsyncWithHttpInfo
     *
     * Begins a new multipart file upload process.
     *
     * @param  \BytescalePHP\Client\Model\BeginMultipartUploadRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function beginMultipartUploadAsyncWithHttpInfo($body, $account_id)
    {
        $returnType = '\BytescalePHP\Client\Model\BeginMultipartUploadResponse';
        $request = $this->beginMultipartUploadRequest($body, $account_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'beginMultipartUpload'
     *
     * @param  \BytescalePHP\Client\Model\BeginMultipartUploadRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function beginMultipartUploadRequest($body, $account_id)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling beginMultipartUpload'
            );
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling beginMultipartUpload'
            );
        }

        $resourcePath = '/v2/accounts/{accountId}/uploads';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation completeUploadPart
     *
     * Marks an upload part as uploaded.  You must call this endpoint after you have successfully issued a `PUT` request to the `uploadUrl` on the corresponding UploadPart.
     *
     * @param  \BytescalePHP\Client\Model\CompleteUploadPartRequest $body body (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index upload_part_index (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function completeUploadPart($body, $account_id, $upload_id, $upload_part_index)
    {
        $this->completeUploadPartWithHttpInfo($body, $account_id, $upload_id, $upload_part_index);
    }

    /**
     * Operation completeUploadPartWithHttpInfo
     *
     * Marks an upload part as uploaded.  You must call this endpoint after you have successfully issued a `PUT` request to the `uploadUrl` on the corresponding UploadPart.
     *
     * @param  \BytescalePHP\Client\Model\CompleteUploadPartRequest $body (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function completeUploadPartWithHttpInfo($body, $account_id, $upload_id, $upload_part_index)
    {
        $returnType = '';
        $request = $this->completeUploadPartRequest($body, $account_id, $upload_id, $upload_part_index);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation completeUploadPartAsync
     *
     * Marks an upload part as uploaded.  You must call this endpoint after you have successfully issued a `PUT` request to the `uploadUrl` on the corresponding UploadPart.
     *
     * @param  \BytescalePHP\Client\Model\CompleteUploadPartRequest $body (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function completeUploadPartAsync($body, $account_id, $upload_id, $upload_part_index)
    {
        return $this->completeUploadPartAsyncWithHttpInfo($body, $account_id, $upload_id, $upload_part_index)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation completeUploadPartAsyncWithHttpInfo
     *
     * Marks an upload part as uploaded.  You must call this endpoint after you have successfully issued a `PUT` request to the `uploadUrl` on the corresponding UploadPart.
     *
     * @param  \BytescalePHP\Client\Model\CompleteUploadPartRequest $body (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function completeUploadPartAsyncWithHttpInfo($body, $account_id, $upload_id, $upload_part_index)
    {
        $returnType = '';
        $request = $this->completeUploadPartRequest($body, $account_id, $upload_id, $upload_part_index);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'completeUploadPart'
     *
     * @param  \BytescalePHP\Client\Model\CompleteUploadPartRequest $body (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function completeUploadPartRequest($body, $account_id, $upload_id, $upload_part_index)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling completeUploadPart'
            );
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling completeUploadPart'
            );
        }
        // verify the required parameter 'upload_id' is set
        if ($upload_id === null || (is_array($upload_id) && count($upload_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_id when calling completeUploadPart'
            );
        }
        // verify the required parameter 'upload_part_index' is set
        if ($upload_part_index === null || (is_array($upload_part_index) && count($upload_part_index) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_part_index when calling completeUploadPart'
            );
        }

        $resourcePath = '/v2/accounts/{accountId}/uploads/{uploadId}/parts/{uploadPartIndex}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($upload_id !== null) {
            $resourcePath = str_replace(
                '{' . 'uploadId' . '}',
                ObjectSerializer::toPathValue($upload_id),
                $resourcePath
            );
        }
        // path params
        if ($upload_part_index !== null) {
            $resourcePath = str_replace(
                '{' . 'uploadPartIndex' . '}',
                ObjectSerializer::toPathValue($upload_part_index),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUploadPart
     *
     * Gets a remaining upload part for a multipart file upload.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index upload_part_index (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BytescalePHP\Client\Model\UploadPart
     */
    public function getUploadPart($account_id, $upload_id, $upload_part_index)
    {
        list($response) = $this->getUploadPartWithHttpInfo($account_id, $upload_id, $upload_part_index);
        return $response;
    }

    /**
     * Operation getUploadPartWithHttpInfo
     *
     * Gets a remaining upload part for a multipart file upload.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BytescalePHP\Client\Model\UploadPart, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUploadPartWithHttpInfo($account_id, $upload_id, $upload_part_index)
    {
        $returnType = '\BytescalePHP\Client\Model\UploadPart';
        $request = $this->getUploadPartRequest($account_id, $upload_id, $upload_part_index);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\UploadPart',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUploadPartAsync
     *
     * Gets a remaining upload part for a multipart file upload.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadPartAsync($account_id, $upload_id, $upload_part_index)
    {
        return $this->getUploadPartAsyncWithHttpInfo($account_id, $upload_id, $upload_part_index)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUploadPartAsyncWithHttpInfo
     *
     * Gets a remaining upload part for a multipart file upload.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadPartAsyncWithHttpInfo($account_id, $upload_id, $upload_part_index)
    {
        $returnType = '\BytescalePHP\Client\Model\UploadPart';
        $request = $this->getUploadPartRequest($account_id, $upload_id, $upload_part_index);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUploadPart'
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     * @param  \BytescalePHP\Client\Model\UploadPartIndex $upload_part_index (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUploadPartRequest($account_id, $upload_id, $upload_part_index)
    {
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getUploadPart'
            );
        }
        // verify the required parameter 'upload_id' is set
        if ($upload_id === null || (is_array($upload_id) && count($upload_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_id when calling getUploadPart'
            );
        }
        // verify the required parameter 'upload_part_index' is set
        if ($upload_part_index === null || (is_array($upload_part_index) && count($upload_part_index) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_part_index when calling getUploadPart'
            );
        }

        $resourcePath = '/v2/accounts/{accountId}/uploads/{uploadId}/parts/{uploadPartIndex}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($upload_id !== null) {
            $resourcePath = str_replace(
                '{' . 'uploadId' . '}',
                ObjectSerializer::toPathValue($upload_id),
                $resourcePath
            );
        }
        // path params
        if ($upload_part_index !== null) {
            $resourcePath = str_replace(
                '{' . 'uploadPartIndex' . '}',
                ObjectSerializer::toPathValue($upload_part_index),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listUploadParts
     *
     * Lists the remaining upload parts for a multipart file upload.  An empty array is returned when the upload is complete.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id upload_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BytescalePHP\Client\Model\UploadPartList
     */
    public function listUploadParts($account_id, $upload_id)
    {
        list($response) = $this->listUploadPartsWithHttpInfo($account_id, $upload_id);
        return $response;
    }

    /**
     * Operation listUploadPartsWithHttpInfo
     *
     * Lists the remaining upload parts for a multipart file upload.  An empty array is returned when the upload is complete.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BytescalePHP\Client\Model\UploadPartList, HTTP status code, HTTP response headers (array of strings)
     */
    public function listUploadPartsWithHttpInfo($account_id, $upload_id)
    {
        $returnType = '\BytescalePHP\Client\Model\UploadPartList';
        $request = $this->listUploadPartsRequest($account_id, $upload_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\UploadPartList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listUploadPartsAsync
     *
     * Lists the remaining upload parts for a multipart file upload.  An empty array is returned when the upload is complete.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listUploadPartsAsync($account_id, $upload_id)
    {
        return $this->listUploadPartsAsyncWithHttpInfo($account_id, $upload_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listUploadPartsAsyncWithHttpInfo
     *
     * Lists the remaining upload parts for a multipart file upload.  An empty array is returned when the upload is complete.
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listUploadPartsAsyncWithHttpInfo($account_id, $upload_id)
    {
        $returnType = '\BytescalePHP\Client\Model\UploadPartList';
        $request = $this->listUploadPartsRequest($account_id, $upload_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listUploadParts'
     *
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     * @param  \BytescalePHP\Client\Model\UploadId $upload_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listUploadPartsRequest($account_id, $upload_id)
    {
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling listUploadParts'
            );
        }
        // verify the required parameter 'upload_id' is set
        if ($upload_id === null || (is_array($upload_id) && count($upload_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_id when calling listUploadParts'
            );
        }

        $resourcePath = '/v2/accounts/{accountId}/uploads/{uploadId}/parts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($upload_id !== null) {
            $resourcePath = str_replace(
                '{' . 'uploadId' . '}',
                ObjectSerializer::toPathValue($upload_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadFromUrl
     *
     * Upload from a URL with a single HTTP request:
     *
     * @param  \BytescalePHP\Client\Model\UploadFromUrlRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id account_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BytescalePHP\Client\Model\BasicUploadResponse
     */
    public function uploadFromUrl($body, $account_id)
    {
        list($response) = $this->uploadFromUrlWithHttpInfo($body, $account_id);
        return $response;
    }

    /**
     * Operation uploadFromUrlWithHttpInfo
     *
     * Upload from a URL with a single HTTP request:
     *
     * @param  \BytescalePHP\Client\Model\UploadFromUrlRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \BytescalePHP\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BytescalePHP\Client\Model\BasicUploadResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadFromUrlWithHttpInfo($body, $account_id)
    {
        $returnType = '\BytescalePHP\Client\Model\BasicUploadResponse';
        $request = $this->uploadFromUrlRequest($body, $account_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\BasicUploadResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BytescalePHP\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation uploadFromUrlAsync
     *
     * Upload from a URL with a single HTTP request:
     *
     * @param  \BytescalePHP\Client\Model\UploadFromUrlRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadFromUrlAsync($body, $account_id)
    {
        return $this->uploadFromUrlAsyncWithHttpInfo($body, $account_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadFromUrlAsyncWithHttpInfo
     *
     * Upload from a URL with a single HTTP request:
     *
     * @param  \BytescalePHP\Client\Model\UploadFromUrlRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadFromUrlAsyncWithHttpInfo($body, $account_id)
    {
        $returnType = '\BytescalePHP\Client\Model\BasicUploadResponse';
        $request = $this->uploadFromUrlRequest($body, $account_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadFromUrl'
     *
     * @param  \BytescalePHP\Client\Model\UploadFromUrlRequest $body File upload parameters. (required)
     * @param  \BytescalePHP\Client\Model\AccountId $account_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function uploadFromUrlRequest($body, $account_id)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling uploadFromUrl'
            );
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling uploadFromUrl'
            );
        }

        $resourcePath = '/v2/accounts/{accountId}/uploads/url';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountId' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
