<?php
/**
 * AwsRegion
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bytescale\Model;
use \Bytescale\ObjectSerializer;

/**
 * AwsRegion Class Doc Comment
 *
 * @category Class
 * @description AWS Region.
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AwsRegion
{
    /**
     * Possible values of this enum
     */
    public const US_EAST_2 = 'us-east-2';

    public const US_EAST_1 = 'us-east-1';

    public const US_WEST_1 = 'us-west-1';

    public const US_WEST_2 = 'us-west-2';

    public const AF_SOUTH_1 = 'af-south-1';

    public const AP_EAST_1 = 'ap-east-1';

    public const AP_SOUTH_2 = 'ap-south-2';

    public const AP_SOUTHEAST_3 = 'ap-southeast-3';

    public const AP_SOUTHEAST_4 = 'ap-southeast-4';

    public const AP_SOUTH_1 = 'ap-south-1';

    public const AP_NORTHEAST_3 = 'ap-northeast-3';

    public const AP_NORTHEAST_2 = 'ap-northeast-2';

    public const AP_SOUTHEAST_1 = 'ap-southeast-1';

    public const AP_SOUTHEAST_2 = 'ap-southeast-2';

    public const AP_NORTHEAST_1 = 'ap-northeast-1';

    public const CA_CENTRAL_1 = 'ca-central-1';

    public const CA_WEST_1 = 'ca-west-1';

    public const EU_CENTRAL_1 = 'eu-central-1';

    public const EU_WEST_1 = 'eu-west-1';

    public const EU_WEST_2 = 'eu-west-2';

    public const EU_SOUTH_1 = 'eu-south-1';

    public const EU_WEST_3 = 'eu-west-3';

    public const EU_SOUTH_2 = 'eu-south-2';

    public const EU_NORTH_1 = 'eu-north-1';

    public const EU_CENTRAL_2 = 'eu-central-2';

    public const IL_CENTRAL_1 = 'il-central-1';

    public const ME_SOUTH_1 = 'me-south-1';

    public const ME_CENTRAL_1 = 'me-central-1';

    public const SA_EAST_1 = 'sa-east-1';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::US_EAST_2,
            self::US_EAST_1,
            self::US_WEST_1,
            self::US_WEST_2,
            self::AF_SOUTH_1,
            self::AP_EAST_1,
            self::AP_SOUTH_2,
            self::AP_SOUTHEAST_3,
            self::AP_SOUTHEAST_4,
            self::AP_SOUTH_1,
            self::AP_NORTHEAST_3,
            self::AP_NORTHEAST_2,
            self::AP_SOUTHEAST_1,
            self::AP_SOUTHEAST_2,
            self::AP_NORTHEAST_1,
            self::CA_CENTRAL_1,
            self::CA_WEST_1,
            self::EU_CENTRAL_1,
            self::EU_WEST_1,
            self::EU_WEST_2,
            self::EU_SOUTH_1,
            self::EU_WEST_3,
            self::EU_SOUTH_2,
            self::EU_NORTH_1,
            self::EU_CENTRAL_2,
            self::IL_CENTRAL_1,
            self::ME_SOUTH_1,
            self::ME_CENTRAL_1,
            self::SA_EAST_1
        ];
    }
}


