<?php
/**
 * AwsRegion
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * AwsRegion Class Doc Comment
 *
 * @category Class
 * @description AWS Region.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AwsRegion
{
    /**
     * Possible values of this enum
     */
    const US_EAST_2 = 'us-east-2';
    const US_EAST_1 = 'us-east-1';
    const US_WEST_1 = 'us-west-1';
    const US_WEST_2 = 'us-west-2';
    const AF_SOUTH_1 = 'af-south-1';
    const AP_EAST_1 = 'ap-east-1';
    const AP_SOUTHEAST_3 = 'ap-southeast-3';
    const AP_SOUTH_1 = 'ap-south-1';
    const AP_NORTHEAST_3 = 'ap-northeast-3';
    const AP_NORTHEAST_2 = 'ap-northeast-2';
    const AP_SOUTHEAST_1 = 'ap-southeast-1';
    const AP_SOUTHEAST_2 = 'ap-southeast-2';
    const AP_NORTHEAST_1 = 'ap-northeast-1';
    const CA_CENTRAL_1 = 'ca-central-1';
    const EU_CENTRAL_1 = 'eu-central-1';
    const EU_WEST_1 = 'eu-west-1';
    const EU_WEST_2 = 'eu-west-2';
    const EU_SOUTH_1 = 'eu-south-1';
    const EU_WEST_3 = 'eu-west-3';
    const EU_NORTH_1 = 'eu-north-1';
    const ME_SOUTH_1 = 'me-south-1';
    const SA_EAST_1 = 'sa-east-1';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::US_EAST_2
            self::US_EAST_1
            self::US_WEST_1
            self::US_WEST_2
            self::AF_SOUTH_1
            self::AP_EAST_1
            self::AP_SOUTHEAST_3
            self::AP_SOUTH_1
            self::AP_NORTHEAST_3
            self::AP_NORTHEAST_2
            self::AP_SOUTHEAST_1
            self::AP_SOUTHEAST_2
            self::AP_NORTHEAST_1
            self::CA_CENTRAL_1
            self::EU_CENTRAL_1
            self::EU_WEST_1
            self::EU_WEST_2
            self::EU_SOUTH_1
            self::EU_WEST_3
            self::EU_NORTH_1
            self::ME_SOUTH_1
            self::SA_EAST_1
        ];
    }
}
