<?php
/**
 * DigitalOceanStorageCredentials
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bytescale\Model;

use \ArrayAccess;
use \Bytescale\ObjectSerializer;

/**
 * DigitalOceanStorageCredentials Class Doc Comment
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DigitalOceanStorageCredentials implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DigitalOceanStorage_credentials';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'spacesSecretKey' => 'string',
        'spacesAccessKey' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'spacesSecretKey' => null,
        'spacesAccessKey' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'spacesSecretKey' => false,
        'spacesAccessKey' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'spacesSecretKey' => 'spacesSecretKey',
        'spacesAccessKey' => 'spacesAccessKey'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'spacesSecretKey' => 'setSpacesSecretKey',
        'spacesAccessKey' => 'setSpacesAccessKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'spacesSecretKey' => 'getSpacesSecretKey',
        'spacesAccessKey' => 'getSpacesAccessKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('spacesSecretKey', $data ?? [], null);
        $this->setIfExists('spacesAccessKey', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['spacesSecretKey'] === null) {
            $invalidProperties[] = "'spacesSecretKey' can't be null";
        }
        if ((mb_strlen($this->container['spacesSecretKey']) > 128)) {
            $invalidProperties[] = "invalid value for 'spacesSecretKey', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['spacesSecretKey']) < 30)) {
            $invalidProperties[] = "invalid value for 'spacesSecretKey', the character length must be bigger than or equal to 30.";
        }

        if (!preg_match("/^\\S*$/", $this->container['spacesSecretKey'])) {
            $invalidProperties[] = "invalid value for 'spacesSecretKey', must be conform to the pattern /^\\S*$/.";
        }

        if ($this->container['spacesAccessKey'] === null) {
            $invalidProperties[] = "'spacesAccessKey' can't be null";
        }
        if ((mb_strlen($this->container['spacesAccessKey']) > 128)) {
            $invalidProperties[] = "invalid value for 'spacesAccessKey', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['spacesAccessKey']) < 16)) {
            $invalidProperties[] = "invalid value for 'spacesAccessKey', the character length must be bigger than or equal to 16.";
        }

        if (!preg_match("/^\\S*$/", $this->container['spacesAccessKey'])) {
            $invalidProperties[] = "invalid value for 'spacesAccessKey', must be conform to the pattern /^\\S*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets spacesSecretKey
     *
     * @return string
     */
    public function getSpacesSecretKey()
    {
        return $this->container['spacesSecretKey'];
    }

    /**
     * Sets spacesSecretKey
     *
     * @param string $spacesSecretKey AWS Secret Access Key.
     *
     * @return self
     */
    public function setSpacesSecretKey($spacesSecretKey)
    {
        if (is_null($spacesSecretKey)) {
            throw new \InvalidArgumentException('non-nullable spacesSecretKey cannot be null');
        }
        if ((mb_strlen($spacesSecretKey) > 128)) {
            throw new \InvalidArgumentException('invalid length for $spacesSecretKey when calling DigitalOceanStorageCredentials., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($spacesSecretKey) < 30)) {
            throw new \InvalidArgumentException('invalid length for $spacesSecretKey when calling DigitalOceanStorageCredentials., must be bigger than or equal to 30.');
        }
        if ((!preg_match("/^\\S*$/", ObjectSerializer::toString($spacesSecretKey)))) {
            throw new \InvalidArgumentException("invalid value for \$spacesSecretKey when calling DigitalOceanStorageCredentials., must conform to the pattern /^\\S*$/.");
        }

        $this->container['spacesSecretKey'] = $spacesSecretKey;

        return $this;
    }

    /**
     * Gets spacesAccessKey
     *
     * @return string
     */
    public function getSpacesAccessKey()
    {
        return $this->container['spacesAccessKey'];
    }

    /**
     * Sets spacesAccessKey
     *
     * @param string $spacesAccessKey AWS Access Key.
     *
     * @return self
     */
    public function setSpacesAccessKey($spacesAccessKey)
    {
        if (is_null($spacesAccessKey)) {
            throw new \InvalidArgumentException('non-nullable spacesAccessKey cannot be null');
        }
        if ((mb_strlen($spacesAccessKey) > 128)) {
            throw new \InvalidArgumentException('invalid length for $spacesAccessKey when calling DigitalOceanStorageCredentials., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($spacesAccessKey) < 16)) {
            throw new \InvalidArgumentException('invalid length for $spacesAccessKey when calling DigitalOceanStorageCredentials., must be bigger than or equal to 16.');
        }
        if ((!preg_match("/^\\S*$/", ObjectSerializer::toString($spacesAccessKey)))) {
            throw new \InvalidArgumentException("invalid value for \$spacesAccessKey when calling DigitalOceanStorageCredentials., must conform to the pattern /^\\S*$/.");
        }

        $this->container['spacesAccessKey'] = $spacesAccessKey;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


