<?php
/**
 * FileDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bytescale\Model;

use \ArrayAccess;
use \Bytescale\ObjectSerializer;

/**
 * FileDetails Class Doc Comment
 *
 * @category Class
 * @description Contains full information about a file, including its file metadata, file tags, original file name, and MIME type.
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FileDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FileDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'accountId' => 'string',
        'metadata' => 'array<string,mixed>',
        'mime' => 'string',
        'originalFileName' => 'string',
        'tags' => 'string[]',
        'filePath' => 'string',
        'fileUrl' => 'string',
        'lastModified' => 'int',
        'size' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'accountId' => null,
        'metadata' => null,
        'mime' => null,
        'originalFileName' => null,
        'tags' => null,
        'filePath' => null,
        'fileUrl' => null,
        'lastModified' => 'int32',
        'size' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'accountId' => false,
        'metadata' => false,
        'mime' => false,
        'originalFileName' => true,
        'tags' => false,
        'filePath' => false,
        'fileUrl' => false,
        'lastModified' => false,
        'size' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accountId' => 'accountId',
        'metadata' => 'metadata',
        'mime' => 'mime',
        'originalFileName' => 'originalFileName',
        'tags' => 'tags',
        'filePath' => 'filePath',
        'fileUrl' => 'fileUrl',
        'lastModified' => 'lastModified',
        'size' => 'size'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accountId' => 'setAccountId',
        'metadata' => 'setMetadata',
        'mime' => 'setMime',
        'originalFileName' => 'setOriginalFileName',
        'tags' => 'setTags',
        'filePath' => 'setFilePath',
        'fileUrl' => 'setFileUrl',
        'lastModified' => 'setLastModified',
        'size' => 'setSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accountId' => 'getAccountId',
        'metadata' => 'getMetadata',
        'mime' => 'getMime',
        'originalFileName' => 'getOriginalFileName',
        'tags' => 'getTags',
        'filePath' => 'getFilePath',
        'fileUrl' => 'getFileUrl',
        'lastModified' => 'getLastModified',
        'size' => 'getSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('accountId', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('mime', $data ?? [], null);
        $this->setIfExists('originalFileName', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('filePath', $data ?? [], null);
        $this->setIfExists('fileUrl', $data ?? [], null);
        $this->setIfExists('lastModified', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['accountId'] === null) {
            $invalidProperties[] = "'accountId' can't be null";
        }
        if ((mb_strlen($this->container['accountId']) > 7)) {
            $invalidProperties[] = "invalid value for 'accountId', the character length must be smaller than or equal to 7.";
        }

        if ((mb_strlen($this->container['accountId']) < 7)) {
            $invalidProperties[] = "invalid value for 'accountId', the character length must be bigger than or equal to 7.";
        }

        if (!preg_match("/^[1-9A-HJ-NP-Za-km-z]*$/", $this->container['accountId'])) {
            $invalidProperties[] = "invalid value for 'accountId', must be conform to the pattern /^[1-9A-HJ-NP-Za-km-z]*$/.";
        }

        if ($this->container['metadata'] === null) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['mime'] === null) {
            $invalidProperties[] = "'mime' can't be null";
        }
        if ((mb_strlen($this->container['mime']) > 255)) {
            $invalidProperties[] = "invalid value for 'mime', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['mime']) < 3)) {
            $invalidProperties[] = "invalid value for 'mime', the character length must be bigger than or equal to 3.";
        }

        if (!preg_match("/^[a-zA-Z0-9]+\/[a-zA-Z0-9+\\-._]+(?:;[^=]+=[^;]+)*$/", $this->container['mime'])) {
            $invalidProperties[] = "invalid value for 'mime', must be conform to the pattern /^[a-zA-Z0-9]+\/[a-zA-Z0-9+\\-._]+(?:;[^=]+=[^;]+)*$/.";
        }

        if ($this->container['originalFileName'] === null) {
            $invalidProperties[] = "'originalFileName' can't be null";
        }
        if ((mb_strlen($this->container['originalFileName']) > 255)) {
            $invalidProperties[] = "invalid value for 'originalFileName', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['originalFileName']) < 1)) {
            $invalidProperties[] = "invalid value for 'originalFileName', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^.+$/", $this->container['originalFileName'])) {
            $invalidProperties[] = "invalid value for 'originalFileName', must be conform to the pattern /^.+$/.";
        }

        if ($this->container['tags'] === null) {
            $invalidProperties[] = "'tags' can't be null";
        }
        if ($this->container['filePath'] === null) {
            $invalidProperties[] = "'filePath' can't be null";
        }
        if ((mb_strlen($this->container['filePath']) > 512)) {
            $invalidProperties[] = "invalid value for 'filePath', the character length must be smaller than or equal to 512.";
        }

        if ((mb_strlen($this->container['filePath']) < 1)) {
            $invalidProperties[] = "invalid value for 'filePath', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^\/.*$/", $this->container['filePath'])) {
            $invalidProperties[] = "invalid value for 'filePath', must be conform to the pattern /^\/.*$/.";
        }

        if ($this->container['fileUrl'] === null) {
            $invalidProperties[] = "'fileUrl' can't be null";
        }
        if ((mb_strlen($this->container['fileUrl']) > 255)) {
            $invalidProperties[] = "invalid value for 'fileUrl', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['fileUrl']) < 1)) {
            $invalidProperties[] = "invalid value for 'fileUrl', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^https?:\/\/[-a-zA-Z0-9]+(?:\\.[-a-zA-Z0-9]+)+(\/.*)?$/", $this->container['fileUrl'])) {
            $invalidProperties[] = "invalid value for 'fileUrl', must be conform to the pattern /^https?:\/\/[-a-zA-Z0-9]+(?:\\.[-a-zA-Z0-9]+)+(\/.*)?$/.";
        }

        if ($this->container['lastModified'] === null) {
            $invalidProperties[] = "'lastModified' can't be null";
        }
        if (($this->container['lastModified'] < 0)) {
            $invalidProperties[] = "invalid value for 'lastModified', must be bigger than or equal to 0.";
        }

        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        if (($this->container['size'] < 0)) {
            $invalidProperties[] = "invalid value for 'size', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accountId
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param string $accountId Your account ID.  This is visible on the settings page:  https://www.bytescale.com/dashboard/settings
     *
     * @return self
     */
    public function setAccountId($accountId)
    {
        if (is_null($accountId)) {
            throw new \InvalidArgumentException('non-nullable accountId cannot be null');
        }
        if ((mb_strlen($accountId) > 7)) {
            throw new \InvalidArgumentException('invalid length for $accountId when calling FileDetails., must be smaller than or equal to 7.');
        }
        if ((mb_strlen($accountId) < 7)) {
            throw new \InvalidArgumentException('invalid length for $accountId when calling FileDetails., must be bigger than or equal to 7.');
        }
        if ((!preg_match("/^[1-9A-HJ-NP-Za-km-z]*$/", ObjectSerializer::toString($accountId)))) {
            throw new \InvalidArgumentException("invalid value for \$accountId when calling FileDetails., must conform to the pattern /^[1-9A-HJ-NP-Za-km-z]*$/.");
        }

        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,mixed>
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,mixed> $metadata The file metadata specified in the original upload request as a JSON object.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets mime
     *
     * @return string
     */
    public function getMime()
    {
        return $this->container['mime'];
    }

    /**
     * Sets mime
     *
     * @param string $mime File MIME type.
     *
     * @return self
     */
    public function setMime($mime)
    {
        if (is_null($mime)) {
            throw new \InvalidArgumentException('non-nullable mime cannot be null');
        }
        if ((mb_strlen($mime) > 255)) {
            throw new \InvalidArgumentException('invalid length for $mime when calling FileDetails., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($mime) < 3)) {
            throw new \InvalidArgumentException('invalid length for $mime when calling FileDetails., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^[a-zA-Z0-9]+\/[a-zA-Z0-9+\\-._]+(?:;[^=]+=[^;]+)*$/", ObjectSerializer::toString($mime)))) {
            throw new \InvalidArgumentException("invalid value for \$mime when calling FileDetails., must conform to the pattern /^[a-zA-Z0-9]+\/[a-zA-Z0-9+\\-._]+(?:;[^=]+=[^;]+)*$/.");
        }

        $this->container['mime'] = $mime;

        return $this;
    }

    /**
     * Gets originalFileName
     *
     * @return string
     */
    public function getOriginalFileName()
    {
        return $this->container['originalFileName'];
    }

    /**
     * Sets originalFileName
     *
     * @param string $originalFileName The file's original name on the user's device.
     *
     * @return self
     */
    public function setOriginalFileName($originalFileName)
    {
        if (is_null($originalFileName)) {
            array_push($this->openAPINullablesSetToNull, 'originalFileName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('originalFileName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($originalFileName) && (mb_strlen($originalFileName) > 255)) {
            throw new \InvalidArgumentException('invalid length for $originalFileName when calling FileDetails., must be smaller than or equal to 255.');
        }
        if (!is_null($originalFileName) && (mb_strlen($originalFileName) < 1)) {
            throw new \InvalidArgumentException('invalid length for $originalFileName when calling FileDetails., must be bigger than or equal to 1.');
        }
        if (!is_null($originalFileName) && (!preg_match("/^.+$/", ObjectSerializer::toString($originalFileName)))) {
            throw new \InvalidArgumentException("invalid value for \$originalFileName when calling FileDetails., must conform to the pattern /^.+$/.");
        }

        $this->container['originalFileName'] = $originalFileName;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[] $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets filePath
     *
     * @return string
     */
    public function getFilePath()
    {
        return $this->container['filePath'];
    }

    /**
     * Sets filePath
     *
     * @param string $filePath Absolute path to a file. Begins with a `/`.
     *
     * @return self
     */
    public function setFilePath($filePath)
    {
        if (is_null($filePath)) {
            throw new \InvalidArgumentException('non-nullable filePath cannot be null');
        }
        if ((mb_strlen($filePath) > 512)) {
            throw new \InvalidArgumentException('invalid length for $filePath when calling FileDetails., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($filePath) < 1)) {
            throw new \InvalidArgumentException('invalid length for $filePath when calling FileDetails., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^\/.*$/", ObjectSerializer::toString($filePath)))) {
            throw new \InvalidArgumentException("invalid value for \$filePath when calling FileDetails., must conform to the pattern /^\/.*$/.");
        }

        $this->container['filePath'] = $filePath;

        return $this;
    }

    /**
     * Gets fileUrl
     *
     * @return string
     */
    public function getFileUrl()
    {
        return $this->container['fileUrl'];
    }

    /**
     * Sets fileUrl
     *
     * @param string $fileUrl URL for a raw file hosted on the Bytescale CDN.
     *
     * @return self
     */
    public function setFileUrl($fileUrl)
    {
        if (is_null($fileUrl)) {
            throw new \InvalidArgumentException('non-nullable fileUrl cannot be null');
        }
        if ((mb_strlen($fileUrl) > 255)) {
            throw new \InvalidArgumentException('invalid length for $fileUrl when calling FileDetails., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($fileUrl) < 1)) {
            throw new \InvalidArgumentException('invalid length for $fileUrl when calling FileDetails., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^https?:\/\/[-a-zA-Z0-9]+(?:\\.[-a-zA-Z0-9]+)+(\/.*)?$/", ObjectSerializer::toString($fileUrl)))) {
            throw new \InvalidArgumentException("invalid value for \$fileUrl when calling FileDetails., must conform to the pattern /^https?:\/\/[-a-zA-Z0-9]+(?:\\.[-a-zA-Z0-9]+)+(\/.*)?$/.");
        }

        $this->container['fileUrl'] = $fileUrl;

        return $this;
    }

    /**
     * Gets lastModified
     *
     * @return int
     */
    public function getLastModified()
    {
        return $this->container['lastModified'];
    }

    /**
     * Sets lastModified
     *
     * @param int $lastModified Epoch milliseconds (since midnight 1 January 1970, UTC).
     *
     * @return self
     */
    public function setLastModified($lastModified)
    {
        if (is_null($lastModified)) {
            throw new \InvalidArgumentException('non-nullable lastModified cannot be null');
        }

        if (($lastModified < 0)) {
            throw new \InvalidArgumentException('invalid value for $lastModified when calling FileDetails., must be bigger than or equal to 0.');
        }

        $this->container['lastModified'] = $lastModified;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int $size Size in bytes.
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }

        if (($size < 0)) {
            throw new \InvalidArgumentException('invalid value for $size when calling FileDetails., must be bigger than or equal to 0.');
        }

        $this->container['size'] = $size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


