<?php
/**
 * PathPermissionScope
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PathPermissionScope Class Doc Comment
 *
 * @category Class
 * @description Specifies the level in the file tree, relative to the path, that these permissions apply.  - &#x60;\&quot;This\&quot;&#x60;: Permissions apply to the current path only.  - &#x60;\&quot;Children\&quot;&#x60;: Permissions apply to the children (files and folders) of this path only.  - &#x60;\&quot;Grandchildren+\&quot;&#x60;: Permissions apply to the grandchildren (files and folders) of this path and their descendants only.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PathPermissionScope
{
    /**
     * Possible values of this enum
     */
    const CHILDREN = 'Children';
    const GRANDCHILDREN = 'Grandchildren+';
    const THIS = 'This';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHILDREN
            self::GRANDCHILDREN
            self::THIS
        ];
    }
}
