<?php
/**
 * PickR2StorageExcludeKeyofR2StorageCredentialsBucket
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bytescale\Model;

use \ArrayAccess;
use \Bytescale\ObjectSerializer;

/**
 * PickR2StorageExcludeKeyofR2StorageCredentialsBucket Class Doc Comment
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PickR2StorageExcludeKeyofR2StorageCredentialsBucket implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Pick_R2Storage_Exclude_keyofR2Storage_credentials___bucket';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'objectKeyPrefix' => 'string',
        'bucketName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'objectKeyPrefix' => null,
        'bucketName' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'objectKeyPrefix' => false,
        'bucketName' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'objectKeyPrefix' => 'objectKeyPrefix',
        'bucketName' => 'bucketName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'objectKeyPrefix' => 'setObjectKeyPrefix',
        'bucketName' => 'setBucketName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'objectKeyPrefix' => 'getObjectKeyPrefix',
        'bucketName' => 'getBucketName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('objectKeyPrefix', $data ?? [], null);
        $this->setIfExists('bucketName', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['objectKeyPrefix'] === null) {
            $invalidProperties[] = "'objectKeyPrefix' can't be null";
        }
        if ((mb_strlen($this->container['objectKeyPrefix']) > 1024)) {
            $invalidProperties[] = "invalid value for 'objectKeyPrefix', the character length must be smaller than or equal to 1024.";
        }

        if ((mb_strlen($this->container['objectKeyPrefix']) < 0)) {
            $invalidProperties[] = "invalid value for 'objectKeyPrefix', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/^\\S*$/", $this->container['objectKeyPrefix'])) {
            $invalidProperties[] = "invalid value for 'objectKeyPrefix', must be conform to the pattern /^\\S*$/.";
        }

        if ($this->container['bucketName'] === null) {
            $invalidProperties[] = "'bucketName' can't be null";
        }
        if ((mb_strlen($this->container['bucketName']) > 61)) {
            $invalidProperties[] = "invalid value for 'bucketName', the character length must be smaller than or equal to 61.";
        }

        if ((mb_strlen($this->container['bucketName']) < 1)) {
            $invalidProperties[] = "invalid value for 'bucketName', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/(?!(^xn--|-s3alias$))^[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$/", $this->container['bucketName'])) {
            $invalidProperties[] = "invalid value for 'bucketName', must be conform to the pattern /(?!(^xn--|-s3alias$))^[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets objectKeyPrefix
     *
     * @return string
     */
    public function getObjectKeyPrefix()
    {
        return $this->container['objectKeyPrefix'];
    }

    /**
     * Sets objectKeyPrefix
     *
     * @param string $objectKeyPrefix AWS S3 Object Key.
     *
     * @return self
     */
    public function setObjectKeyPrefix($objectKeyPrefix)
    {
        if (is_null($objectKeyPrefix)) {
            throw new \InvalidArgumentException('non-nullable objectKeyPrefix cannot be null');
        }
        if ((mb_strlen($objectKeyPrefix) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $objectKeyPrefix when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must be smaller than or equal to 1024.');
        }
        if ((mb_strlen($objectKeyPrefix) < 0)) {
            throw new \InvalidArgumentException('invalid length for $objectKeyPrefix when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/^\\S*$/", ObjectSerializer::toString($objectKeyPrefix)))) {
            throw new \InvalidArgumentException("invalid value for \$objectKeyPrefix when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must conform to the pattern /^\\S*$/.");
        }

        $this->container['objectKeyPrefix'] = $objectKeyPrefix;

        return $this;
    }

    /**
     * Gets bucketName
     *
     * @return string
     */
    public function getBucketName()
    {
        return $this->container['bucketName'];
    }

    /**
     * Sets bucketName
     *
     * @param string $bucketName AWS S3 Bucket Name.
     *
     * @return self
     */
    public function setBucketName($bucketName)
    {
        if (is_null($bucketName)) {
            throw new \InvalidArgumentException('non-nullable bucketName cannot be null');
        }
        if ((mb_strlen($bucketName) > 61)) {
            throw new \InvalidArgumentException('invalid length for $bucketName when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must be smaller than or equal to 61.');
        }
        if ((mb_strlen($bucketName) < 1)) {
            throw new \InvalidArgumentException('invalid length for $bucketName when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/(?!(^xn--|-s3alias$))^[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$/", ObjectSerializer::toString($bucketName)))) {
            throw new \InvalidArgumentException("invalid value for \$bucketName when calling PickR2StorageExcludeKeyofR2StorageCredentialsBucket., must conform to the pattern /(?!(^xn--|-s3alias$))^[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$/.");
        }

        $this->container['bucketName'] = $bucketName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


