<?php

/**
 * CopyableFileDataFileMetadata_Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BytescalePHP\Client;

use PHPUnit\Framework\TestCase;

/**
 * CopyableFileDataFileMetadata_Test Class Doc Comment
 *
 * @category    Class
 * @description CopyableFileDataFileMetadata_
 * @package     BytescalePHP\Client
 * @author      BytescalePHP Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CopyableFileDataFileMetadata_Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CopyableFileDataFileMetadata_"
     */
    public function testCopyableFileDataFileMetadata_()
    {
    }

    /**
     * Test attribute "merge"
     */
    public function testPropertyMerge()
    {
    }

    /**
     * Test attribute "set_for_all_artifacts"
     */
    public function testPropertySetForAllArtifacts()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }
}
