<?php

/**
 * FileDownloadGrantsArrayTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BytescalePHP\Client;

use PHPUnit\Framework\TestCase;

/**
 * FileDownloadGrantsArrayTest Class Doc Comment
 *
 * @category    Class
 * @description An array of transformation URL slug patterns.  This array specifies which transformation slugs can be used when downloading files from this location.  - Use &#x60;\&quot;*\&quot;&#x60; to allow all file downloads.  - Use &#x60;\&quot;raw\&quot;&#x60; to allow raw/original file downloads.  - Use a &#x60;*&#x60; suffix to allow transformation prefixes. For example: &#x60;\&quot;thumbnail-*\&quot;&#x60; will allow &#x60;thumbnail-sm&#x60; and &#x60;thumbnail-lg&#x60;.  - Use any other value to allow specific transformations. For example: &#x60;\&quot;thumbnail\&quot;&#x60; will allow &#x60;thumbnail&#x60; downloads only.  - Use an empty array to indicate no file downloads are allowed.
 * @package     BytescalePHP\Client
 * @author      BytescalePHP Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileDownloadGrantsArrayTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FileDownloadGrantsArray"
     */
    public function testFileDownloadGrantsArray()
    {
    }
}
