<?php

/**
 * FolderPathTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BytescalePHP\Client;

use PHPUnit\Framework\TestCase;

/**
 * FolderPathTest Class Doc Comment
 *
 * @category    Class
 * @description Absolute path to a folder. Begins with a &#x60;/&#x60;. Should not end with a &#x60;/&#x60;.
 * @package     BytescalePHP\Client
 * @author      BytescalePHP Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FolderPathTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FolderPath"
     */
    public function testFolderPath()
    {
    }
}
