<?php
/**
 * FolderSettingsInheritedTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Bytescale\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FolderSettingsInheritedTest Class Doc Comment
 *
 * @category    Class
 * @description The FolderSettings inherited by the current path.  If the folder defines its own &#x60;settings&#x60;, then those will take effect instead of these inherited settings.  Each inherited setting contains a &#x60;folderPath&#x60; field to indicate which folder the setting was inherited from.  Note: if the requester has insufficient privileges to read a setting, that setting&#39;s value will be undefined.
 * @package     Bytescale
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FolderSettingsInheritedTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FolderSettingsInherited"
     */
    public function testFolderSettingsInherited()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "publicPermissions"
     */
    public function testPropertyPublicPermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "storageLayer"
     */
    public function testPropertyStorageLayer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
