<?php

/**
 * PickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BytescalePHP\Client;

use PHPUnit\Framework\TestCase;

/**
 * PickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucketTest Class Doc Comment
 *
 * @category    Class
 * @description PickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucket
 * @package     BytescalePHP\Client
 * @author      BytescalePHP Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucketTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucket"
     */
    public function testPickDigitalOceanStorageExcludeKeyofDigitalOceanStorageCredentialsBucket()
    {
    }

    /**
     * Test attribute "object_key_prefix"
     */
    public function testPropertyObjectKeyPrefix()
    {
    }

    /**
     * Test attribute "bucket_region"
     */
    public function testPropertyBucketRegion()
    {
    }

    /**
     * Test attribute "bucket_name"
     */
    public function testPropertyBucketName()
    {
    }
}
