<?php
/**
 * PutFolderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PutFolderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request body for PutFolder.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PutFolderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PutFolderRequest"
     */
    public function testPutFolderRequest()
    {
    }

    /**
     * Test attribute "allow_unnamed_folder"
     */
    public function testPropertyAllowUnnamedFolder()
    {
    }

    /**
     * Test attribute "folder_path"
     */
    public function testPropertyFolderPath()
    {
    }

    /**
     * Test attribute "folder_settings"
     */
    public function testPropertyFolderSettings()
    {
    }
}
