<?php
/**
 * RelativeOrAbsoluteFilePathTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RelativeOrAbsoluteFilePathTest Class Doc Comment
 *
 * @category    Class
 * @description Absolute or relative path to a location in your Bytescale account&#x27;s storage.  Relative paths are relative to the API key&#x27;s default folder (configured per API key in the Bytescale Dashboard).  Does not support path traversals (e.g. &#x60;..&#x60;).  Does not support path variables.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RelativeOrAbsoluteFilePathTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RelativeOrAbsoluteFilePath"
     */
    public function testRelativeOrAbsoluteFilePath()
    {
    }
}
