<?php

/**
 * UploadPartIndexTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BytescalePHP\Client;

use PHPUnit\Framework\TestCase;

/**
 * UploadPartIndexTest Class Doc Comment
 *
 * @category    Class
 * @description Index of an uploadable file part.  Can be used as the &#x60;uploadPartIndex&#x60; parameter in the GetUploadPart and CompleteUploadPart operations.
 * @package     BytescalePHP\Client
 * @author      BytescalePHP Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadPartIndexTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UploadPartIndex"
     */
    public function testUploadPartIndex()
    {
    }
}
