<?php

/**
 * FileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * BytescalePHP Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BytescalePHP\Client;

use BytescalePHP\Client\Configuration;
use BytescalePHP\Client\ApiException;
use BytescalePHP\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  BytescalePHP\Client
 * @author   BytescalePHP Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for copyFile
     *
     * Copies a file synchronously..
     *
     */
    public function testCopyFile()
    {
    }

    /**
     * Test case for copyFileBatch
     *
     * Copies multiple files asynchronously..
     *
     */
    public function testCopyFileBatch()
    {
    }

    /**
     * Test case for deleteFile
     *
     * Deletes a file synchronously.  Requires a `secret_*` API key. Alternatively, you can use a `public_*` API key and JWT-based auth..
     *
     */
    public function testDeleteFile()
    {
    }

    /**
     * Test case for deleteFileBatch
     *
     * Deletes multiple files asynchronously.  Requires a `secret_*` API key. Alternatively, you can use a `public_*` API key and JWT-based auth..
     *
     */
    public function testDeleteFileBatch()
    {
    }

    /**
     * Test case for downloadFile
     *
     * Downloads a file in its original/unprocessed state..
     *
     */
    public function testDownloadFile()
    {
    }

    /**
     * Test case for getFileDetails
     *
     * Gets the full details (e.g. metadata, tags, etc.) for a file..
     *
     */
    public function testGetFileDetails()
    {
    }

    /**
     * Test case for processFile
     *
     * Processes a file and returns the result..
     *
     */
    public function testProcessFile()
    {
    }

    /**
     * Test case for processFileAndSave
     *
     * Processes a file and saves the result..
     *
     */
    public function testProcessFileAndSave()
    {
    }
}
