<?php
/**
 * FileApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * @bytescale/api
 *
 * Bytescale API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@bytescale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bytescale\Test\Api;

use \Bytescale\Configuration;
use \Bytescale\ApiException;
use \Bytescale\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bytescale
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for copyFile
     *
     * Copies a file synchronously..
     *
     */
    public function testCopyFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for copyFileBatch
     *
     * Copies multiple files asynchronously..
     *
     */
    public function testCopyFileBatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFile
     *
     * Deletes a file synchronously.  Requires a `secret_*` API key. Alternatively, you can use a `public_*` API key and JWT-based auth..
     *
     */
    public function testDeleteFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFileBatch
     *
     * Deletes multiple files asynchronously.  Requires a `secret_*` API key. Alternatively, you can use a `public_*` API key and JWT-based auth..
     *
     */
    public function testDeleteFileBatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadFile
     *
     * Downloads a file in its original/unprocessed state..
     *
     */
    public function testDownloadFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFileDetails
     *
     * Gets the full details (e.g. metadata, tags, etc.) for a file..
     *
     */
    public function testGetFileDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processFile
     *
     * Processes a file and returns the result..
     *
     */
    public function testProcessFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processFileAndSave
     *
     * Processes a file and saves the result..
     *
     */
    public function testProcessFileAndSave()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
